services:
  app:
    build: ./Server/Preschool
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASS=secret
      - DB_NAME=mydb

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: mydb
    ports:
      - "3306:3306"

  angular-app:
    build:
      context: ./Client/e-uprava
      dockerfile: Dockerfile
    container_name: angular-app
    ports:
      - 4200:4200
    volumes:
      - ./Client/e-uprava:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
